### ISSUE TITLE
Undefined local variable or method 'default'

### ISSUE THREAD

**Issue by luckymike** [spox/bogo-cli#2]
Using `bogo-cli` 0.1.26 with `sfn` wrapped `knife cloudformation` I see the following error on a create command:
```
/Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bogo-cli-0.1.26/lib/bogo-cli/command.rb:105:in `load_config!': undefined local variable or method `default' for #<Sfn::Command::Create:0x007fe9efb06ab8> (NameError)
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bogo-cli-0.1.26/lib/bogo-cli/command.rb:42:in `initialize'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sfn-0.4.12/lib/sfn/command.rb:25:in `initialize'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sfn-0.4.12/lib/chef/knife/knife_plugin_seed.rb:78:in `new'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sfn-0.4.12/lib/chef/knife/knife_plugin_seed.rb:78:in `run'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.6.2/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.6.2/lib/chef/knife.rb:173:in `run'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.6.2/lib/chef/application/knife.rb:123:in `run'
        from /Users/z644181/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.6.2/bin/knife:25:in `<top (required)>'
        from /Users/z644181/.rbenv/versions/2.1.2/bin/knife:23:in `load'
        from /Users/z644181/.rbenv/versions/2.1.2/bin/knife:23:in `<main>'
```

Pinning to 0.1.24 resolves it.

**Comment by chrisroberts** [comment]
Fixed via #3
